# config information for China 2024 project initial setup

[settings]
model_type = "WEO" # or "non-WEO"
scenario_year_pairs = [["Announced Pledges Scenario", 2022,], ["Announced Pledges Scenario", 2030], ["Stated Policies Scenario", 2030]]

# path to files needed for setup such as generator parameters etc
[path]
generator_parameters_path = "S:/China/2024_China_EFC/01_Data/02_PowerPlants/2024_03_2_generator_parameters_China_0.1_updating_plant_list.xlsx"
transmission_path = 
load_path = 
model_xml_path = "S:/China/2024_China_EFC/03_Modelling/China_2024_proj_1.7_New_zone_etc.xml"

## how the plexos model is configured internally, e.g. region object contains single nodes or all nodes
## there are some legacy differences between the models and there are some advantages, e.g. the Region object allows for more queries than Node
[model_setup]
main_node_object = "Node" # for some models could be Region
main_aggregate_object = "Region" # for some models could be Area or Zone
secondary_node_object = "Zone" # for models with Region as the primary object, Node is typically the secondary
secondary_aggregate_object = None # This could be Area or Zone

## whether to populate the solution index sheet model objects using user made Excel sheets or a model xml export
[solution_index_source]
transmission = "user Excel"
generation = "user Excel"
fuel = "xml export"
emission= "xml export"


